### ISSUE TITLE
Could not find any "avro-typeable" sub types of my sealed trait/companion obj

### ISSUE THREAD

**Issue by seglo** [GenslerAppsPod/scalavro#46]
I'm trying to get the schema of the following.

```
sealed trait Health { def code: Int }
object Health {
  case object Nominal extends Health {val code = 0}
  case object Warning extends Health {val code = 1}
  case object Critical extends Health {val code = 2}
}
```
But I get the following exception
```
Could not find any avro-typeable sub types of [bp.Health]
java.lang.IllegalArgumentException: Could not find any avro-typeable sub types of [bp.Health]
	at com.gensler.scalavro.types.complex.AvroUnion$.fromType(AvroUnion.scala:140)
	at com.gensler.scalavro.types.AvroType$$anonfun$fromTypeHelper$1.apply(AvroType.scala:301)
	at com.gensler.scalavro.types.AvroType$$anonfun$fromTypeHelper$1.apply(AvroType.scala:252)
	at scala.util.Try$.apply(Try.scala:161)
	at com.gensler.scalavro.types.AvroType$.fromTypeHelper(AvroType.scala:252)
	at com.gensler.scalavro.types.AvroType$.fromType(AvroType.scala:248)
	at com.gensler.scalavro.types.AvroType$.apply(AvroType.scala:235)
	at bp.SerializationSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(SerializationSpec.scala:24)
	at bp.SerializationSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(SerializationSpec.scala:21)
	at bp.SerializationSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(SerializationSpec.scala:21)
	at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FreeSpecLike$$anon$1.apply(FreeSpecLike.scala:373)
	at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
	at org.scalatest.FreeSpec.withFixture(FreeSpec.scala:1740)
	at org.scalatest.FreeSpecLike$class.invokeWithFixture$1(FreeSpecLike.scala:370)
	at org.scalatest.FreeSpecLike$$anonfun$runTest$1.apply(FreeSpecLike.scala:382)
	at org.scalatest.FreeSpecLike$$anonfun$runTest$1.apply(FreeSpecLike.scala:382)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	at org.scalatest.FreeSpecLike$class.runTest(FreeSpecLike.scala:382)
	at org.scalatest.FreeSpec.runTest(FreeSpec.scala:1740)
	at org.scalatest.FreeSpecLike$$anonfun$runTests$1.apply(FreeSpecLike.scala:441)
	at org.scalatest.FreeSpecLike$$anonfun$runTests$1.apply(FreeSpecLike.scala:441)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
	at org.scalatest.FreeSpecLike$class.runTests(FreeSpecLike.scala:441)
	at org.scalatest.FreeSpec.runTests(FreeSpec.scala:1740)
	at org.scalatest.Suite$class.run(Suite.scala:1424)
	at org.scalatest.FreeSpec.org$scalatest$FreeSpecLike$$super$run(FreeSpec.scala:1740)
	at org.scalatest.FreeSpecLike$$anonfun$run$1.apply(FreeSpecLike.scala:486)
	at org.scalatest.FreeSpecLike$$anonfun$run$1.apply(FreeSpecLike.scala:486)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
	at org.scalatest.FreeSpecLike$class.run(FreeSpecLike.scala:486)
	at org.scalatest.FreeSpec.run(FreeSpec.scala:1740)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2563)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2557)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2557)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1044)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1043)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2722)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1043)
	at org.scalatest.tools.Runner$.run(Runner.scala:883)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:138)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

Also when I attempt to run your example for Scala sealed case objects I get the same error.

```
sealed trait Color
object Color {
  case object Black extends Color
  case object White extends Color
  case object Blue extends Color
}

AvroType[Color].schema
```

**Comment by anayyar82** [comment]
Did it get resolved

**Comment by dyk** [comment]
@seglo have you tried master?

**Comment by seglo** [comment]
@dyk I didn't.  I ended up not using scalavro for that project.  Hopefully someone else can reproduce with the information provided, otherwise feel free to close this ticket.
