### ISSUE TITLE
 Could not find any avro-typeable sub types

### ISSUE THREAD

**Issue by anayyar82** [GenslerAppsPod/scalavro#47]
I have case class, while generating schema, getting issue :

Exception in thread "main" java.lang.IllegalArgumentException: Could not find any avro-typeable sub types of [com.test.generated.TicketType]
	at com.gensler.scalavro.types.complex.AvroUnion$.fromType(AvroUnion.scala:140)
	at com.gensler.scalavro.types.AvroType$$anonfun$fromTypeHelper$1.apply(AvroType.scala:301)
	at com.gensler.scalavro.types.AvroType$$anonfun$fromTypeHelper$1.apply(AvroType.scala:252)
	at scala.util.Try$.apply(Try.scala:161)
	at com.gensler.scalavro.types.AvroType$.fromTypeHelper(AvroType.scala:252)
	at com.gensler.scalavro.types.AvroType$.fromType(AvroType.scala:248)
	at com.gensler.scalavro.types.AvroType$.apply(AvroType.scala:235)
	at com.gensler.scalavro.types.complex.AvroRecord$Field.fieldType$lzycompute(AvroRecord.scala:113)
	at com.gensler.scalavro.types.complex.AvroRecord$Field.fieldType(AvroRecord.scala:113)

Below is the program to run : 

val test = AvroType[Ticket]
    test.schema
    println(test.schemaOrName())
  }

Case classes :::::::::::::: 

case class Nodes(node: com.test.spark.generated.NodeType*)

  case class Logs(log: com.test.spark.generated.LogType*)

  case class Ticket(description: String,
                    typeValue: com.test.spark.generated.TicketType,
                    severity: com.test.spark.generated.SeverityType,
                    start: javax.xml.datatype.XMLGregorianCalendar,
                    expected: javax.xml.datatype.XMLGregorianCalendar,
                    finished: Option[javax.xml.datatype.XMLGregorianCalendar] = None,
                    nodes: Option[com.test.spark.generated.Nodes] = None,
                    logs: Option[com.test.spark.generated.Logs] = None,
                    attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
    lazy val id = attributes.get("@id") map { _.as[Int] }
    lazy val status = attributes.get("@status") map { _.as[StatusType] }
  }

  case class NodeType(name: String,
                      master: Boolean,
                      reason: String,
                      customers: Int,
                      affected: com.test.spark.generated.AffectedType,
                      attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
    lazy val id = attributes.get("@id") map { _.as[Int] }
  }

  case class AffectedType(spid: Seq[com.test.spark.generated.SpidType] = Nil,
                          product: Seq[com.test.spark.generated.ProductType] = Nil)

  case class ProductType(value: Int,
                         attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
    lazy val typeValue = attributes.get("@type") map { _.as[String] }
  }

  case class SpidType(value: Int,
                      attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
    lazy val id = attributes.get("@id") map { _.as[Int] }
  }

  case class AnkurType(name: String,
                       master: Boolean,
                       reason: String,
                       customers: Int,
                       affected: com.test.spark.generated.AffectedType,
                       attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
    lazy val id = attributes.get("@id") map { _.as[Int] }
  }

  case class LogType(text: String,
                     time: javax.xml.datatype.XMLGregorianCalendar,
                     typeValue: String,
                     attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
    lazy val id = attributes.get("@id") map { _.as[Int] }
  }

  trait StatusType

  object StatusType {
    def fromString(value: String, scope: scala.xml.NamespaceBinding): StatusType = value match {
      case "open" => Open
      case "closed" => Closed

    }
  }

  case object Open extends StatusType { override def toString = "open" }
  case object Closed extends StatusType { override def toString = "closed" }

  trait TicketType

  object TicketType {
    def fromString(value: String, scope: scala.xml.NamespaceBinding): TicketType = value match {
      case "acute" => Acute
      case "planned" => Planned
      case "auto" => Auto

    }
  }

  case object Acute extends TicketType { override def toString = "acute" }
  case object Planned extends TicketType { override def toString = "planned" }
  case object Auto extends TicketType { override def toString = "auto" }

  trait SeverityType

  object SeverityType {
    def fromString(value: String, scope: scala.xml.NamespaceBinding): SeverityType = value match {
      case "stop" => Stop
      case "disturbance" => Disturbance
      case "info" => Info

    }
  }

  case object Stop extends SeverityType { override def toString = "stop" }
  case object Disturbance extends SeverityType { override def toString = "disturbance" }
  case object Info extends SeverityType { override def toString = "info" }

**Comment by dyk** [comment]
What version are you using? Released? From master?
